version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lyceum_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-lyceum_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: lyceum_redis
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: lyceum_bot
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./creds:/app/creds
    environment:
      - POSTGRESQL_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-lyceum_db}
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: